Fix clippy warning about "loop never loops"
This warning was introduced with the previous commit.

error: this loop never actually loops
   --> src/main.rs:543:13
    |
543 | /             for entry in net_entries.flatten() {
544 | |                 let path = entry.path().file_name()?.to_string_lossy().to_string();
545 | |                 return Some(path);
546 | |             }
    | |_____________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#never_loop
    = note: `#[deny(clippy::never_loop)]` on by default
help: if you need the first element of the iterator, try writing
    |
543 |             if let Some(entry) = net_entries.flatten().next() {
    |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Uli Schlachter <psychon@znc.in>